title: Son HO
email: t DASH sonho AT microsoft DOT com
description: Azure Research, Cambridge UK

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sonho.fr/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sonmarcho
github_username:  sonmarcho

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-postfiles
